### ISSUE TITLE
Release 0.9.2

### ISSUE THREAD

**Issue by barthez** [scrogson/oauth2#101]
Hello @scrogson,

Would you mind to release new version of oauth2 that contains fixes from https://github.com/scrogson/oauth2/pull/98? I'm struggling with the same issues that author was struggling at that time. Please 😃 .

Thanks a mill,
Bartek

**Comment by scrogson** [comment]
Done!

https://github.com/scrogson/oauth2/releases/tag/v0.9.2

**Comment by barthez** [comment]
❤️ 💙 💚 💛 💜
