### ISSUE TITLE
Document the way to use the different strategies

### ISSUE THREAD

**Issue by benzen** [scrogson/oauth2#103]
There is at least three strategies. 
And only one is explained in plain text.

We need more doc in order to use this

**Comment by benzen** [comment]
I'm looking for documentation of how to use the strategy, not creating my own strategy

**Comment by scrogson** [comment]
Here is an example of how to use the `AuthCode` strategy: https://github.com/scrogson/oauth2#authorization-code-flow-authcode-strategy

The other strategies are similar, but after looking again at the README and the docs, I see that I need better docs.

Thanks for pointing that out @benzen
