### ISSUE TITLE
Doesn't seem to pass client_secret when getting a token

### ISSUE THREAD

**Issue by kluufger** [scrogson/oauth2#108]
Not sure if it's actually needed, but passing client secret in params makes it work with google.

```elixir
  def get_token!(params \\ [], headers \\ []) do
    OAuth2.Client.get_token!(client(), params ++ [{:client_secret, unquote(client_secret)}])
  end
```

Otherwise google returns
```elixir
%{"error" => "invalid_request", "error_description" => "client_secret is missing."}
```

**Comment by scrogson** [comment]
@kluufger yep, that's Google's requirement which should be added in a Google specific strategy. This library is meant to serve as a base OAuth2 client.

**Comment by kluufger** [comment]
@scrogson thanks for clarifying it.

Should https://github.com/scrogson/oauth2_example/blob/master/web/oauth/google.ex be updated then? Would you like me to submit a PR?

**Comment by scrogson** [comment]
@kluufger there are already many PRs on that repo to do just that...I haven't gotten around to reviewing/merging any of them.
