### ISSUE TITLE
Error: no match of right hand side value: :undefined

### ISSUE THREAD

**Issue by bshaffer** [scrogson/oauth2#110]
Hello! Fantastic library!
When I run your oauth2-example repository, everything works as expected. However, when I create a phoenix app from scratch and use the same code, I get the following error:

# no match of right hand side value: :undefined

The code line this is on is as follows:
```
  def callback(conn, %{"code" => code}) do
    # Exchange an auth code for an access token
    client = Google.get_token!(code: code)
    # ....
  end
```

I've been trying everything to get this code to return, and nothing I do changes the error. I've changed `client` to `:undefined`, with no luck. Any help is appreciated!

**Comment by scrogson** [comment]
@bshaffer can you provide a link to some code? Or provide a project that produces the error you're seeing? Without that, I can't really be too much help.
