### ISSUE TITLE
Question can this be used with coherence?

### ISSUE THREAD

**Issue by AlmogRnD** [scrogson/oauth2#113]
Wanted to know if this can be used with Coherence package?

**Comment by scrogson** [comment]
@AlmogRnD I haven't every used `coherence` so I can't comment on that. But it does look like Coherence has a lot in common with Devise (Ruby). Maybe the equivalent of the Omniauthable strategy would be Ueberauthable?

In that case, maybe @smpallen99 would have a better understanding on how that would fit together?

**Comment by AlmogRnD** [comment]
@scrogson I got it working using an hex package, closing this

**Comment by scrogson** [comment]
@AlmogRnD can you post a link to the hex package? It would be nice to document for others that might have the same question.

**Comment by AlmogRnD** [comment]
Sure it's https://github.com/danschultzer/coherence_assent
