### ISSUE TITLE
How to get refresh token with Strategy AuthCode

### ISSUE THREAD

**Issue by peter-sf** [scrogson/oauth2#129]
Hello! I'm trying to follow this sample to handle Google OAuth inside my project. 
I have a problem because I'm not sure what I have to do to get `refresh_token`. Actually, I'm getting only `access_token`

`%OAuth2.Client{
  authorize_url: "/o/oauth2/auth",
  client_id: "xxxx",
  client_secret: "xxxx",
  headers: [],
  params: %{},
  redirect_uri: "http://localhost:4000/redirect",
  ref: nil,
  request_opts: [],
  serializers: %{},
  site: "https://accounts.google.com",
  strategy: OAuth2.Strategy.AuthCode,
  token: %OAuth2.AccessToken{
    access_token: "{\n  \"access_token\": \"xxxx\",\n  \"expires_in\": 3599,\n  \"scope\": \"https://www.googleapis.com/auth/userinfo.email openid\",\n  \"token_type\": \"Bearer\",\n  \"id_token\": \"xxxx\"\n}",
    expires_at: nil,
    other_params: %{},
    refresh_token: nil,
    token_type: "Bearer"
  },`

Many thanks for the help!

**Comment by scrogson** [comment]
Hi @peter-sf,

Which version are you using? From the looks of your example above, it appears that your access token was not parsed (JSON).

If you're using `v1.0`, you'll need to register a JSON serialize as described [here](https://github.com/scrogson/oauth2#configure-a-serializer).

Hope that helps!
