### ISSUE TITLE
Not able get access token with ClientCredentials strategy

### ISSUE THREAD

**Issue by joobisb** [scrogson/oauth2#135]
@scrogson This is my curl request and I'm getting the access token successfully.
`curl -X POST --user <client_id>:<client_secret> '<site_url>/oauth2/token?grant_type=client_credentials' -H 'Content-Type: application/x-www-form-urlencoded'`

Following are the steps I followed

```
client = OAuth2.Client.new([
  strategy: OAuth2.Strategy.ClientCredentials,
  client_id: "<client_id>",
  client_secret: "<client_secret>",
  site: "<site_url>",
  token_url: "/oauth2/token",
  headers: [
  {"content-type", "application/x-www-form-urlencoded"}
  ]
])

response = OAuth2.Client.get_token(client)
```

I,m getting response as 405 method not allowed as below

```
{:error,
 %OAuth2.Response{
   body: "",
   headers: [
     {"date", "Sun, 05 May 2019 12:18:00 GMT"},
     {"content-length", "0"},
     {"connection", "keep-alive"},
     {"set-cookie",
      "XSRF-TOKEN=<xsrf-token>; Path=/; Secure; HttpOnly"},
     {"x-amz-cognito-request-id", "<req_id>"},
     {"x-application-context", "application:prod:8443"},
     {"x-content-type-options", "nosniff"},
     {"x-xss-protection", "1; mode=block"},
     {"cache-control", "no-cache, no-store, max-age=0, must-revalidate"},
     {"pragma", "no-cache"},
     {"expires", "0"},
     {"strict-transport-security", "max-age=<max-age> ; includeSubDomains"},
     {"x-frame-options", "DENY"},
     {"server", "Server"},
     {"allow", "GET"}
   ],
   status_code: 405
 }}
```

**Comment by scrogson** [comment]
@joobisb can you please try with `master`?

**Comment by joobisb** [comment]
@scrogson I tried by importing this in mix.exs

def application do
  # Add the application to your list of applications.
  # This will ensure that it will be included in a release.
  [applications: [:logger, :oauth2]]
end

defp deps do
  # Add the dependency
  [{:oauth2, "~> 1.0"}]
end

What should I do to try in master?

**Comment by scrogson** [comment]
```ex
{:oauth2, github: “scrogson/oauth2”}
```

**Comment by joobisb** [comment]
@scrogson I tried but still getting same error response

**Comment by scrogson** [comment]
I believe the content-type is set for you automatically.

**Comment by scrogson** [comment]
Just to make sure...did you run `mix does.update oauth2` after changing the dependency in `mix.exs`?

**Comment by joobisb** [comment]
yes I did that

**Comment by joobisb** [comment]
@scrogson So what might be the issue?

**Comment by scrogson** [comment]
Next thing to try is to turn on hackney tracing and figure out what is being sent to the server. Place this before the call to `get_token`:


```ex
:hackney_trace.enable(:max, :io)
```

**Comment by joobisb** [comment]
@scrogson The issue is solved. By default the accept and content-type header was `application/x-www-form-urlencoded` and that was causing the problem.  I changed accept header to `*/*` and I got the access token. Thanks for helping me to trace it out.
