### ISSUE TITLE
Global Serializer Registration

### ISSUE THREAD

**Issue by sheharyarn** [scrogson/oauth2#139]
After v1.0.0, we have to specify serializers for each client manually. While it makes sense to have the ability to specify serializers on a per-client basis, `oauth2` should've kept the global serializer config map so clients can fallback to global specifications when they're not explicitly set.

TL;DR: I want to bring back this:

```elixir
config :oauth2,
  serializers: %{
    "application/json" => Jason,
    "application/xml" => MyApp.Parsers.XML
  }
```

**Comment by scrogson** [comment]
Hi @sheharyarn, I'm not interested in supporting/maintaining this approach any longer (which is why I removed it).

This can simply be supported in a function call:

```ex
def new do
  %OAuth2.Client{}
  |> put_serializer("application/json", Jason)
  |> put_serializer("application/xml", XML)
end
```
