### ISSUE TITLE
Tuple {:option, :server_only, :honor_cipher_order} being returned for error reason

### ISSUE THREAD

**Issue by keithpitty** [scrogson/oauth2#144]
The application I'm supporting has OAuth authentication using two different authentication servers. Mysteriously, only in my development environment they have begun exhibiting unexpected behaviour.

When an attempt is made to get a token via `OAuth2.Client.get_token/1`, an error is returned with a tuple rather than a string for the reason. The value of the tuple is `{:option, :server_only, :honor_cipher_order}`. I haven't been able to find out why this is happening nor what the tuple means.

Any help would be appreciated.

**Comment by keithpitty** [comment]
Discovered that this was caused by https://github.com/benoitc/hackney/issues/591 following an upgrade on my machine to Erlang 22.1.

**Comment by BartOtten** [comment]
Can be fixed by updating the dep.

` {:hackney, "~> 1.15 and >= 1.15.2"},`
