### ISSUE TITLE
Implement scope attribute to make it useable with Google

### ISSUE THREAD

**Issue by philippkueng** [scrogson/oauth2#15]
Hi Sonny,

I'm wondering if Google OAuth support is already on your roadmap and/or if you would welcome any help in the form of PRs?

From looking at a couple of libraries from other languages so far, implementing additional providers always seems a mess. Therefore I kind of like the approach that @hapijs took with [bell](https://github.com/hapijs/bell), with this library could can define custom provider attributes in a map, thinking this would be fairly trivial to do in Elixir. Or would you prefer multiple different strategies implemented using your library as the base? (eg. https://github.com/zquestz/omniauth-google-oauth2)

What's your opinion on this?

**Comment by scrogson** [comment]
`scope` is simply a query string param that can be passed into the `authorize_url` function. So what you're asking for is already supported.

When making your own strategy you can simply use `put_param` to add the `scope` to to the `params` key on the client struct.

Have a look at the `README`. I've got an example of how you can build your own strategy for GitHub.

Hope that helps.

**Comment by philippkueng** [comment]
@scrogson omg, I'm really sorry, that's quite embarrassing.
Thought I double checked the readme. Thanks very much for clarifying it and helping me out.

Cheers
