### ISSUE TITLE
Respond with error when token is expired

### ISSUE THREAD

**Issue by vitaliel** [scrogson/oauth2#17]
Server headers:

[[{"Server", "nginx"}, {"Date", "Mon, 15 Jun 2015 17:43:08 GMT"}, {"Content-Length", "0"}, {"WWW-Authenticate", "Bearer realm=\"Service\", error=\"invalid_token\", error_description=\"The access token provided is invalid.\""}, {"Age", "0"}, {"Connection", "keep-alive"}]

and body is blank. Stack trace:

** (Poison.SyntaxError) Unexpected end of input
             lib/poison/parser.ex:54: Poison.Parser.parse!/2
             lib/poison.ex:83: Poison.decode!/2
    (oauth2) lib/oauth2/response.ex:35: OAuth2.Response.new/3
    (oauth2) lib/oauth2/request.ex:43: OAuth2.Request.handle_request_body/3
    (oauth2) lib/oauth2/access_token.ex:59: OAuth2.AccessToken.get/4

**Comment by scrogson** [comment]
@vitaliel thank you. I will look into this soon.

**Comment by scrogson** [comment]
@vitaliel this should be fixed on master. Please give it a try and let me know.
