### ISSUE TITLE
Make Content-Type in token_post_header configurable

### ISSUE THREAD

**Issue by optikfluffel** [scrogson/oauth2#23]
Hi, for getting an access-token from the SoundCloud API I had to change [`lib/oauth2/client.ex#L177`](https://github.com/scrogson/oauth2/blob/master/lib/oauth2/client.ex#L177) from
```elixir
put_header(client, "Content-Type", "application/x-www-form-urlencoded")
```
to
```elixir
put_header(client, "Content-Type", "application/json")
```
otherwise I'd just get a `406` with an empty body back.
Is there a way to configure this or build it into my own strategy?

Thanks

**Comment by scrogson** [comment]
Hi @optikfluffel,

You will want to create your own custom strategy for this.

Have a look at the example custom strategy I made in the README [here]. If you look at the `get_token` function you'll see that I'm setting the "Accept" header there. You can do the same for the "Content-Type".

Let me know if you need any further help.

[here]: https://github.com/scrogson/oauth2#write-your-own-strategy
