### ISSUE TITLE
Shopify Strategy

### ISSUE THREAD

**Issue by djinn** [scrogson/oauth2#24]
I was following your example interface. I have hit a road block with Shopify Strategy. The code requires dynamic url for site, auth and token. Wondering how to incorporate that in the example?

**Comment by scrogson** [comment]
@djinn looking at the [Shopify documentation], it looks like the base url is the same for all requests: https://{shop}.myshopify.com.

So I think the config for your strategy would be something like:

```elixir
...
site: "https://{shop}.myshopify.com",
authorize_url: "/admin/oauth/authorize",
token_url: "/admin/oauth/access_token",
...
```

Let me know if this doesn't solve your issue.
[Shopify documentation]: https://docs.shopify.com/api/authentication/oauth

**Comment by djinn** [comment]
Thanks. 
I found in strategy file new function signature conflicted with OAuth.Client.new in case, I added argument. I modified new to create function and called that in authorize_url! and token_url!.

Now works.
```elixir
def create(shopid) do
  OAuth2.new([
    strategy: __MODULE__,
    client_id: System.get_env("CLIENT_ID"),
    client_secret:  System.get_env("CLIENT_SECRET"),
    redirect_uri: System.get_env("REDIRECT_URI"),
    site: "https://#{shopid}.myshopify.com/admin",
    authorize_url: "https://#{shopid}.myshopify.com/admin/oauth/authorize",
    token_url: "https://#{shopid}.myshopify.com/admin/token"
    ])
end

def authorize_url!(shopid, params \\ []) do
  OAuth2.Client.authorize_url!(create(shopid), params)
end

def get_token!(shopid, params \\ [], headers \\ []) do
  OAuth2.Client.get_token!(create(shopid), params)
end
```

**Comment by scrogson** [comment]
Awesome!
