### ISSUE TITLE
Unauthorized responses from the provider are considered successful responses 

### ISSUE THREAD

**Issue by meatherly** [scrogson/oauth2#37]
As of now when the provider returns a 401 status the `OAuth2.AccessToken.get/2` function returns a `{:ok, response}` tuple. This seems misleading. Shouldn't this be an error? I can have a pull request ready if you feel like this is an issue.

**Comment by scrogson** [comment]
Hey @meatherly, yeah, I'm aware of this issue and I've got some work in progress to try and resolve it.

The problem is...the HTTP request was actually a success (you're getting back a response and it was parsed correctly).

Should anything in the `400..599` range return `{:error, error}`? I don't like that.

Thoughts?

**Comment by meatherly** [comment]
I can see what you mean by not liking anything that comes back between `400..599` as an error because that doesn't mean it's necessarily an error. Seeing that the functionality of the module `OAuth2.AccessToken` is supposed to contact the oauth provider with the access token now makes it feel like a http client and in that case you'd want'd want to know what to do if the response was successful, not if the the body of the response was parsed right.  That make sense?

Here's an example below. What happens is a mobile client will send me a access token that I will then use to contact the server to make sure the user is valid. If the access_token is invalid I would not want to save the user.

```
case OAuth2.AccessToken.get(bad_access_token, "/some/resource") do
    {:ok, response} ->
      user = response
        |> create_changeset_from_response
        |> Repo.insert!
      # respond with conn
    {:error, resource}
      # respond with conn and errors
  end
```

When I provide a bad access token I get a 401 response with the body " " (doorkeeper is weird like that).  `get` still gives me a {:ok, response} which then leads me to believe that request we successful and I now can do what I wanted with a successful response. 

I feel like I'm repeating myself and not really going any where and I might just not know what I'm doing lol. Does any of this make sense? 

Since the docs say for `get\2` :
> Makes a `GET` request to the given URL using the AccessToken. 

wouldn't it makes since to have a http client feel to it?

**Comment by scrogson** [comment]
Yes, I think that it should return `{:ok, %OAuth2.Response{}` or `{:error, %OAuth2.Error{}}`.

Right now it's just returning the `body` field, which is poor.

**Comment by meatherly** [comment]
https://github.com/scrogson/oauth2/commit/4081b90a4555e3541953e2f78307bc003583db34#diff-ae6bc7a7e030e0509edda8d602a0b504R18
Thanks!  :+1: 

(even though the code was mostly there on master and i'm an idiot for not realizing it :p )
