### ISSUE TITLE
Changelog Request!

### ISSUE THREAD

**Issue by stavro** [scrogson/oauth2#41]
Please implement a changelog with deprecation notices in the future.

Thanks!

edit: Such as `OAuth2.new` to `OAuth2.Client.new`, and the access token response being returned instead of the body.

**Comment by scrogson** [comment]
Hi @stavro,

I've added a changelog as requested. I have been adding changelogs to the release notes for each release. I'll start adding changes to the changelog and compiling those into release note from now on. Will probably be a better workflow.

Thanks!
