### ISSUE TITLE
encode_query causing issues in OAuth.authorize_url! with params

### ISSUE THREAD

**Issue by waynehoover** [scrogson/oauth2#43]
Hello, I have an API that requires the URL parameters for scope to contain literal `+` and not `%2B` so when I call `OAuth.authorize_url!` it eventually calls `URI.encode_query(client.params)` here https://github.com/scrogson/oauth2/blob/master/lib/oauth2/client.ex#L181 which makes my scope params look like this `scope=public%2Bread_user` instead of what the API expects, i.e. this `scope=public+read_user`

Is there a way I'm not seeing to have it just pass the query params as is without calling `URI.encode_query`? Also in your opinion is this a bug in the API? Seems like it should be ok with both `+` and `%2B` in the url.

Thanks.

**Comment by scrogson** [comment]
Thanks for the report. I don't know the right answer at the moment but I will try to find out.

My gut tells me that the API should handle both. But maybe I need to fix it on my end.

**Comment by meatherly** [comment]
@waynehoover how are you specifying your params? I was looking through the docs for `URI.encode_query/1` and it looks like it shouldn't encode the `+` sign. Take a look and tell me if you're seeing the same thing https://github.com/elixir-lang/elixir/blob/v1.1.1/lib/elixir/lib/uri.ex#L61

**Comment by waynehoover** [comment]
@meatherly the query string is getting passed via options to OAuth.authoriz_url! as a string like "foo+bar+baz" which in turn produces this:

```iex(2)> URI.encode_query(scope: "foo+bar+baz")
"scope=foo%2Bbar%2Bbaz"``
