### ISSUE TITLE
Allow client to receive url as parameter

### ISSUE THREAD

**Issue by ZJvandeWeg** [scrogson/oauth2#44]
Im working on a strategy for a product where one can set up his/her own server, on a chosen location. If Im not overlooking something, at the time of writing this cant be easily done. I would like to pass additional information, like the URL to `#client`.

Please let me know what your opinion is on this.

**Comment by scrogson** [comment]
Hi @ZJvandeWeg can you explain a little bit further what you mean? I have a feeling that you are talking about a dynamic `site` url?

**Comment by ZJvandeWeg** [comment]
Yeah, for instance if I run a GitLab server at home I'd like to use the same strategy as the strategy for gitlab.com. 

Did I clarify it enough?

**Comment by meatherly** [comment]
You could make it receive one if you wrote your own strategy. Or you could write a function that wraps the `Client.new` func.

**Comment by ZJvandeWeg** [comment]
@meatherly Very much true, though I do think it might be better to do it in the oauth2 lib itself as more strategies will need it. For example, Github Enterprise will need it once Oauth2 is supported, ownCloud too. 
I'm fine with your solution, just wondering if there is a common pattern which can be solved just once.

**Comment by ZJvandeWeg** [comment]
@meatherly 
Wow, it _just_ hit me what you really meant. Silly me!
