### ISSUE TITLE
"authorize_url" function always return URL with "client_id: "

### ISSUE THREAD

**Issue by PotterDai** [scrogson/oauth2#46]
"authorize_url" function always return URL with "client_id: "
Is there a way to modify this atom name? 
Some websites request "appid" instead of "client_id" in client authorize URL.

**Comment by scrogson** [comment]
Thanks for the report. I will look into this.

**Comment by scrogson** [comment]
One way to do this would be to just simply add it as a parameter to the request:

```elixir
AuthCode.get_token!(client, appid: client.client_secret, code: "...")
```
