### ISSUE TITLE
:ssl_verify_hostname, "make" command failed

### ISSUE THREAD

**Issue by jlxq0** [scrogson/oauth2#50]
I'm trying to use oauth2 on OS X 10.11.4, but I cannot seem to get my dependencies straight. A `mix deps.get, compile` always results in 
```
==> ssl_verify_hostname
rebar get-deps compile
make: rebar: No such file or directory
make: *** [erl] Error 1
==> cdcoll
** (Mix) Could not compile dependency :ssl_verify_hostname, "make" command failed.
You can recompile this dependency with "mix deps.compile ssl_verify_hostname",
update it with "mix deps.update ssl_verify_hostname" or clean it with "mix deps.clean
ssl_verify_hostname"
```
What am I missing here?

**Comment by scrogson** [comment]
Hi @jlxq0,

What other dependencies do you have in your application?

**Comment by wandelson** [comment]
I have a same problem.


defmodule PluralsightTweet.Mixfile do
  use Mix.Project

  def project do
    [app: :pluralsight_tweet,
     version: "0.1.0",
     elixir: "~> 1.4",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [extra_applications: [:logger, :quantum, :extwitter],
     mod: {PluralsightTweet.Application, []}]
  end

  # Dependencies can be Hex packages:
  #
  #   {:my_dep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:my_dep, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [{:credo, "~> 0.8.4"},
    {:quantum, "~> 1.8"},
    {:oauth, github: "tim/erlang-oauth"},
    {:extwitter, "~> 0.7.2"}]
  end
end
