### ISSUE TITLE
Subclass OAuth2.Request?

### ISSUE THREAD

**Issue by jeffutter** [scrogson/oauth2#56]
I'm wondering if there is any way to 'subclass' Oauth2.Request? I see that it uses HTTPoison.Base. I'm used to defining things like `process_response_body` with HTTPoison. Is there a way to do this with OAuth2?

**Comment by scrogson** [comment]
Hi @jeffutter, at this time, there is not a way to do this. In fact I have [this PR](https://github.com/scrogson/oauth2/pull/52) which removes HTTPoison entirely.

The idea is that you can just specify a serializer module in your config based on the `content-type` header and it will call your serializer for you automatically.
