### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by jeffutter** [scrogson/oauth2#60]
Is there any way a new release could be cut? I'm looking to publish something on hex.pm that uses this as a dep, but I need this commit: https://github.com/scrogson/oauth2/commit/3277a29e182e63de2a497af947cf5145b0944a6b 

Thanks.

**Comment by scrogson** [comment]
Hi @jeffutter, sorry for the delay. I need to ensure that the docs are all up-to-date with the latest changes after merging #52. I need to write a migration guide for folks moving from `0.6` to `0.7` as there are breaking changes. I'm short on time right now so I could use some help if you're up for it.

**Comment by jeffutter** [comment]
Ok, no hurry. I'm also pretty swamped. I'll see If I can pour over the docs some this weekend.

**Comment by jeffutter** [comment]
@scrogson I think that PR ⬆️ is ready for review. I believe I cleaned up most (if not all) of the changes introduced by #52 . The upgrading guide will probably take someones else's care since I only used the library for a couple days on 0.6 before jumping to master.

Let me know if there is anything you would like me to change on my PR or if there is anything else I can help out with.

**Comment by jeffutter** [comment]
@scrogson I might take a stab at an upgrade guide. Would you prefer a separate UPGRADE.md or include it in the breaking change section of the change log?

**Comment by scrogson** [comment]
Hey @jeffutter, changelog would be perfect. Thank you!

**Comment by scrogson** [comment]
@jeffutter I've published `v0.7.0`! Thank you so much for your help with the docs and changelog, that really helped a ton!!!

🎉
