### ISSUE TITLE
Commit 7d5ae39 breaks AuthCode Strategy for GitHub

### ISSUE THREAD

**Issue by smetana** [scrogson/oauth2#64]
The issue is in commit https://github.com/scrogson/oauth2/commit/7d5ae395d65c08f5c053d53b7c240d85f15ee1ee

Removing client_secret from params makes GitHub to return "incorrect_client_credentials"

As per https://developer.github.com/v3/oauth/#web-application-flow client_secret is required to exchange authorization_code for access_token

**Comment by scrogson** [comment]
Hi @smetana, the referenced commit was to make the `AuthCode` strategy compliant with the OAuth 2.0 spec. If GitHub requires that you send the `client_secret` along with the request, then it would need to be added manually.

```elixir
AuthCode.get_token!(client, client_secret: client.client_secret, scope: "...")
```

That should do the trick.

**Comment by smetana** [comment]
It does. Maybe it should be noticed in README because current strategy example does not work.

**Comment by scrogson** [comment]
:+1:

**Comment by yang-wei** [comment]
I can't get this work.
Following the example:

```elixir
## strategy callback

  def get_token(client, params, headers) do
    params = params |> Keyword.merge([client_secret: client.client_secret])
    # [code: "***", client_secret: "***"]
    client
    |> put_header("accept", "application/json")
    |> OAuth2.Strategy.AuthCode.get_token(params, headers)
  end

```

**Comment by yang-wei** [comment]
Ok so i get the token from github but I failed when I request the api:

```elixir


  def callback(conn, %{"code" => code}) do

    client = GitHub.get_token!(code: code)

    user = get_user!(client) # failed here

    conn
    |> put_session(:current_user, user)
    |> redirect(to: "/")

  end

  defp get_user!(client) do
    case OAuth2.Client.get(client, "/user") do
      {:ok, %{status_code: 401, body: body}} ->
        IO.inspect body  # <-- get 401 here
        raise("Unauthorized token")
      {:ok, %{status_code: status_code, body: user}} when status_code in [200..399] ->
        user
      {:error, %{reason: reason}} ->
        Logger.error("Error: #{inspect reason}")
    end
  end

```

**Comment by masonforest** [comment]
@yang-wei try adding

`params = params |> Keyword.merge([client_secret: client.client_secret])`


to `get_token!` instead of `get_token` like I did [here](https://github.com/scrogson/oauth2_example/pull/15/files#diff-c331efda81a1a1acc451de8cd6de457eR28). Does that work?

**Comment by yang-wei** [comment]
I gave up and implemented it by myself.
btw nice pr @masonforest

**Comment by binarytemple** [comment]
@yang-wei care to share a link to your implementation?

**Comment by yang-wei** [comment]
@binarytemple https://github.com/lidashuang/github_oauth

**Comment by binarytemple** [comment]
thanks @yang-wei - I might have to do something custom for Paypal Oauth, understand it isn't quite a standard implementation, hence the ask.
