### ISSUE TITLE
Google strategy not working because of response_type being sent when getting token

### ISSUE THREAD

**Issue by dannytatom** [scrogson/oauth2#65]
```
other_params: %{"error" => "invalid_request",
    "error_description" => "Parameter not allowed for this message type: response_type"}
```

I think because of this?

https://github.com/scrogson/oauth2/blob/master/lib/oauth2/strategy/auth_code.ex#L55

Not really sure tho 'cause no request actually happens here but does happen `Client#get_token`. ¯\_(ツ)_/¯

Either way, how can I get rid of that param when making token request?

**Comment by scrogson** [comment]
@dannytatom thank you for the report! Please try `master`.
