### ISSUE TITLE
Refresh is broken

### ISSUE THREAD

**Issue by beno** [scrogson/oauth2#66]
When I refresh a token, the client incorrectly sends an authorization header (with the expired `access_token`) and an `accepts` header of `application/x-www-form-urlencoded`. The server I am talking to trips over the authorization header and refuses the refresh request.

As an aside, the Poison decoder subsequently trips over the HTML error message, probably because of the accepts header. For some reason I was unable to intercept and print the HTML response (I get a list of binaries like `<<139, 8, 0, 0...>>` that seems to be incomprehensible to Elixir. So this was brutally hard to debug.

**Comment by scrogson** [comment]
Thank you for reporting this. What is the server expecting in your case?

**Comment by beno** [comment]
Hi,

The server wants a wwwformencoded request (as is) with application/json accept header and without any authorization header. Hope this is clear.

Brgds,
Michel

**Comment by scrogson** [comment]
Hello @beno, can you please try `master`?

**Comment by beno** [comment]
Success! I just performed my first token refresh. Thank you.
