### ISSUE TITLE
Default json decoder (Poison) will not be used

### ISSUE THREAD

**Issue by EyMaddis** [scrogson/oauth2#67]
Hi,
since I just spend more than an hour debugging why the authentication did not work.

I use Phoenix which already depends on Poison for JSOn decoding, so I assumed that this would be handled automatically. I also tried to explicitly adding it as a dependency for the application in `mix.exs`.
I now know that I have to manually configure the serializer in my config, but I would suggest to change [this line](https://github.com/scrogson/oauth2/blob/e79054e3c743142bfc288f6cf2d5df65c35af9f8/lib/oauth2/response.ex#L50) to raise an error. Maybe not an error, but I think that just using the plain body leads to a lot of hidden bugs.

I would suggest that a missing decoder should not be ignored silently.

**Comment by scrogson** [comment]
@EyMaddis thanks for the feedback. 

How about adding a `parsed?` field on the `Response` struct?

**Comment by scrogson** [comment]
@EyMaddis I found a bug that sounds related to the problem you experienced. I've fixed it in https://github.com/scrogson/oauth2/commit/fefbce7149482e750b0a649393f09e2ebbfedf1c and have published `0.8.0`. I will keep this issue open until I decide what to do about missing decoders.

**Comment by EyMaddis** [comment]
@scrogson I think that a `parsed` field wouldn't change the issue. If I want to know if it was parsed I can just check the type of the response body. The developer will still need to manually check that property which leads to nasty hidden bugs
