### ISSUE TITLE
Cannot skip url encode!

### ISSUE THREAD

**Issue by liveresume** [scrogson/oauth2#71]
LinkedIn requires parenthesis to indicate parameters to return.  OAuth2 encodes parenthesis to %28 and %29 which results in an error from LinkedIn.  I found this code but it does not work.  Why?

```
  def skip_url_encode_option, do: [hackney: [path_encode_fun: fn a -> a end]]

  def get_user_id!(client) do
    response = OAuth2.Client.get!(client, "/v1/people/~:(id)?format=json", [], skip_url_encode_option)
  end
```

**Comment by fajarmf** [comment]
I believe since we are directly using hackney know since 0.6, your skip_url_encode_option should be modified into:

```
  defp skip_url_encode_option, do: [path_encode_fun: fn(a) -> a end]
```
