### ISSUE TITLE
"client secret cannot be empty" from Yahoo API

### ISSUE THREAD

**Issue by jessejanderson** [scrogson/oauth2#72]
When I try to use `OAuth2.Client.get_token!/2` with a `%OAuth.Client{}` containing the client_id and client_secret, it asks me to include the secret again? It seems like it's supposed to be able to just get that from the included client?

![image](https://cloud.githubusercontent.com/assets/8367129/19402223/c1a854b2-9214-11e6-8052-033136b912da.png)

**Comment by scrogson** [comment]
@jessejanderson please see my comment [here](https://github.com/scrogson/oauth2/pull/69#issuecomment-251752721)

You can just pass it in as a param along with your `code` like so:

```
OAuth2.Client.get_token!(client, code: "authcode", client_secret: client.client_secret)
```

You might want to make a custom `OAuth2.Strategy.Yahoo` module in your app that adheres to Yahoo's specific requirements (some of which are outside of the OAuth2 spec).

**Comment by jessejanderson** [comment]
Doing the custom strategy thing and this was easily fixed up, thanks!
