### ISSUE TITLE
Client.get_token! not parsing correctly for Yahoo API

### ISSUE THREAD

**Issue by jessejanderson** [scrogson/oauth2#73]
After running `OAuth2.Client.get_token!(client, code: "authcode", client_secret: "secret") I get back a `%OAuth2.Client{}` struct with this inside:

`token: %OAuth2.AccessToken{access_token: "{\"access_token\":\"ABC123A\",\"refresh_token\":\"ABC123B\",\"expires_in\":3600,\"token_type\":\"bearer\",\"xoauth_yahoo_guid\":\"ABC123C\"}"`

I'm assuming that it parsed incorrectly, and all of those should be k/v inside of the AccessToken struct.

**Comment by scrogson** [comment]
Hi @jessejanderson,

Did you configure the serializers for the `content-type` that Yahoo is returning? See [here](https://github.com/scrogson/oauth2#configure-a-serializer) in the README.

If you provide that bit of configuration, it should parse it for you automatically.

**Comment by jessejanderson** [comment]
I'm a bit out of my element here, so excuse the obvious newbie-ness. 😬 

For a bit I thought Yahoo was returning `application/x-www-form-urlencoded`, but I think that is just the content-type that is _sent_ to Yahoo with the `Authorization: Basic ABC123` header.

As far as I can tell, the `content-type` returned by Yahoo is just `application/json` because it is being interpreted by Poison. To get it to use a custom serializer (which I have yet to figure out what to do with those `encode!/decode!` functions anyway) I have to change it to:

```config :oauth2,
  serializers: %{
    "application/json" => OathAlpha.YahooParser,
  }```

Which seems, strange to me. Unless Yahoo is just returning something totally borked that Poison's serializer can't understand?

**Comment by scrogson** [comment]
You should not need to define a custom serializer for `application/json`. If you have `Poison` included in your project just configure with:

```elixir
config :oauth2, serializers: %{"application/json" => Poison}
```

It looks like Yahoo is sending you back a token in JSON format, so the `content-type` header should be `application/json`. With the above configuration, `Poison.encode!/1` should be called automatically for you behind the scenes.

**Comment by jessejanderson** [comment]
Right, okay so that's how it's setup - but the problem is what I posted originally where it is throwing everything as a single concatenated string into `token: %OAuth2.AccessToken{access_token: _____}`

**Comment by jessejanderson** [comment]
![image](https://cloud.githubusercontent.com/assets/8367129/19407786/1e217358-9261-11e6-9326-4c2bb1443aac.png)

**Comment by fajarmf** [comment]
I did something along this line with facebook and linkedin when getting the token:
```
%OAuth2.Client{token: token} = Ueberauth.Strategy.Facebook.OAuth.get_token!([code: code], opts)
```
you were passing on a client but the code think of it as a token.

**Comment by scrogson** [comment]
@jessejanderson can you please try with `master`?

I've added an option to allow to debug the responses coming back.

You can enable by adding the following your `config.exs`:

```elixir
config :oauth2, debug: true
```

This will allow you to verify the response coming back from Yahoo has the `content-type` header set correctly or not.

Please give it a shot and let me know.

**Comment by jessejanderson** [comment]
Ahh - fixed it! I didn't have my serializers setup correctly. It defaulted with 
```config :oauth2,
  serializers: %{
    "application/vnd.api+json" => Poison
  }```

and I needed to add another line for `application/json` to Poison.

```config :oauth2,
  serializers: %{
    "application/vnd.api+json" => Poison,
    "application/json" => Poison
  }
```

Thanks @scrogson for helping me find that and providing the debug!
