### ISSUE TITLE
get_token no client_secret in params

### ISSUE THREAD

**Issue by jtzero** [scrogson/oauth2#75]
while using https://github.com/scrogson/oauth2_example (google auth)  in 
```
def get_token(%{token_method: method} = client, params \\ [], headers \\ [], opts \\ []) do
        {client, url} = token_url(client, params, headers)
        case Request.request(method, client, url, client.params, client.headers, opts) do
```
client.params =
```
%{"client_id" => "some_client_id",
  "code" => "5/codestring",
  "grant_type" => "authorization_code",
  "redirect_uri" => "http://localhost:4000/auth/google/callback"}
```

and this ends up throwing 
```
%OAuth2.Response{body: %{"error" => "invalid_request",
    "error_description" => "client_secret is missing."},
```
just to test this theory (because I don't the inner workings) replacing the case line with  
```
case Request.request(method, client, url, Map.put_new(client.params, "client_secret", client.client_secret), client.headers, opts) do
```
and it works.

**Comment by jtzero** [comment]
```@version "0.8.0"```

**Comment by scrogson** [comment]
Hello @jtzero,

Please see #72 for an explanation of this issue.

The issue you are experiencing is not with this repo, but the implementation on the `oauth2_example` repo.

You will need to use `put_param/3` to the `Google` module [here].

```ex
def get_token(client, params, headers) do
  client
  |> put_param(:client_secrect, client.client_secret)
  |> put_header("accept", "application/json")
  |> AuthCode.get_token(params, headers)
end
```

If you want to contribute a fix over there, feel free!

[here]: https://github.com/scrogson/oauth2_example/blob/master/web/oauth/google.ex#L40

**Comment by jtzero** [comment]
awesome thanks for pointing me in the right direction!
