### ISSUE TITLE
feature suggestion: auto refreshing access tokens

### ISSUE THREAD

**Issue by tsubery** [scrogson/oauth2#79]
Hello,

I noticed there is implementation of refresh token and access token. For any long running access the users of the library would have to manually refresh tokens for providers that require it like Google. I think it makes sense to add some logic to automatically refresh expired tokens when making requests. For backward compatibility, we can off by default.
Let me know if you are interested in pull request.

**Comment by scrogson** [comment]
Hi @tsubery,

I'm hesitant to put this directly into this library. This library is meant to provide low-level OAuth2 building blocks.

Can you give me an example of how you are using this library so I can better understand what it is that you expect to accomplish?

Specifically, how are you storing tokens for later use?

**Comment by tsubery** [comment]
My use case is a long running background job that access google's api and collects information periodically. That means I need to store a token that eventually expires and need to be refreshed.

When I wrote the issue I forgot about the immutability of data in Elixir. I was thinking it would be clean and easy to make any request fetch for a new access token using the refresh token when necessary. This would work but the original client would not have the new access token and that might lead to many unnecessary round trips.
I understand that this library does not implement a token store.

Having said that, there is still some minimal amount of logic can be abstracted away from users like me. All I really want is a token that is good for the next few minutes to do the required work. Maybe a function like this would be useful:
```Elixir
def fresh_token_for(client, time_out_seconds) do
   if now() + timeout_seconds < client.token.expired_at do
    refresh_token(client, [],[],[])
  else
    client
  end
end
```

**Comment by scrogson** [comment]
@tsubery,

Yeah, I've thought about including some sort of token store for a while. However, it seems difficult to make something generic enough to work with all use cases without further thought.

**Comment by tsubery** [comment]
Yea, seems like it might be mixing too many responsibilities. What do you think about the new function I suggested?

**Comment by scrogson** [comment]
@tsubery not at this time. Thank you.
