### ISSUE TITLE
DNS_PROBE_FINISHED_BAD_CONFIG

### ISSUE THREAD

**Issue by ponty96** [scrogson/oauth2#80]
Getting this after following the example here https://github.com/scrogson/oauth2_example and implementing for Google

**Comment by scrogson** [comment]
Hi @ponty96 can you please provide some context for this error?

**Comment by ponty96** [comment]
Yeah. So I'm using that example and I'm trying to implement Google Oauth. So when I visit http://localhost:4000/google it redirects to the a Google URL and I get that error on the page. Which I should instead get the page where I sign in to google

**Comment by scrogson** [comment]
I just tried the example app and it worked fine for me. The error you are getting seems unrelated to the example app or this library.

Did you export the necessary environment variables for you Google application for use in the example app?

If not, they are:

```
GOOGLE_CLIENT_ID="<your-client-id>"
GOOGLE_CLIENT_SECRET="<your-client-secret>"
GOOGLE_REDIRECT_URI="http://lvh.me:4000/auth/google/callback"
```

Other than that, I'm not sure what else it could be.

Doing a quick search for the error you provided lead me to this post: http://www.incrediblelab.com/dns-probe-finished-bad-config-error-fixed/

Not sure if that helps...let me know.

**Comment by ponty96** [comment]
yeah. it was a silly error from my end

**Comment by ponty96** [comment]
But I'm getting this now, this is after I accept on the google authorize page
<img width="1115" alt="screen shot 2016-12-08 at 12 03 27 pm" src="https://cloud.githubusercontent.com/assets/11190968/21007711/652a7f62-bd3e-11e6-82cf-3222756a5ba6.png">

**Comment by tsubery** [comment]
@ponty96 If I remember correctly, google requires different credentials for different clients (front/backend). When you create new credentials, they ask what type of client do you need it for. You can try creating new credentials and see if that works.

**Comment by ponty96** [comment]
@tsubery I've tried doing that...  Same issue

**Comment by johannesE** [comment]
I might have the same issue with github:
After getting the token, my client looks like this:
`pry(1)> client
%OAuth2.Client{authorize_url: "https://github.com/login/oauth/authorize",
 client_id: "foo",
 client_secret: "foo", headers: [],
 params: %{}, redirect_uri: "http://localhost:4000/auth/github/callback",
 site: "https://api.github.com", strategy: GitHub,
 token: %OAuth2.AccessToken{access_token: "{\"access_token\":\"foo\",\"token_type\":\"bearer\",\"scope\":\"public_repo,user\"}",
  expires_at: nil, other_params: %{}, refresh_token: nil, token_type: "Bearer"},
 token_method: :post, token_url: "https://github.com/login/oauth/access_token"}`
When I try a request:
`pry(2)> OAuth2.Client.get!(client, "/user").body
"{\"message\":\"Bad credentials\",\"documentation_url\":\"https://developer.github.com/v3\"}"`

Might it be, that the access_token is too deply nested? Is it supposed to look like that?

**Comment by scrogson** [comment]
@johannesE did you set the configuration for the serializers as outlined in the README? It looks like the access token came back fine but wasn't properly parsed.

```ex
config :oauth2, :serializers, %{
  "application/json" => Poison
}
```

**Comment by johannesE** [comment]
Oh my god, that was it. Sorry for wasting your time. Thank you for the help!
