### ISSUE TITLE
Registering serializers

### ISSUE THREAD

**Issue by tsubery** [scrogson/oauth2#88]
I'm writing an oauth strategy that needs an extra serializer. Eventually I want to release it as hex package. I rather avoid instructing the package users to configure oauth2 with the extra serializer if I can avoid it as it might conflict with other libraries. At the moment I just deserialize the response myself. With the latest oauth2 version, the users will get a warning about the missing serializer. The solutions I can think of are:
- Allow flagging request to skip deserialization
- Allow flagging requests to skip warning
- Add serializer registry (maybe ets based?) where libraries that depend on oauth could programmatically add serializers

What are your thoughts?

**Comment by scrogson** [comment]
@tsubery I'm definitely in support of this feature. I will work on something for `v0.10.0`.
