### ISSUE TITLE
connection refused that never hits the server

### ISSUE THREAD

**Issue by ngw** [scrogson/oauth2#94]
Hi, I'm writing a ueberauth adapter for a custom rails application using doorkeeper.
I receive a "connection refused" during the first "handshake", when the provider hits my phoenix app redirect_uri with a code.
This is the client as in OAuth2.Client.get_token (all urls/codes are local obviously):

    %OAuth2.Client{authorize_url: "http://localhost:3000/oauth/authorize",
     client_id: "9e382aae12f43dc6ae767e1b9a15de2f0b08837536109155f28c5392fbb58c34",
     client_secret: "a7c0d53db32622482c6aa2ddab159dbea8d9a37d2fd09518cc2e0ec85660ec4cs",
     headers: [{"content-type", "application/x-www-form-urlencoded"},
      {"accept", "application/json"}],
     params: %{"client_id" => "9e382aae12f43dc6ae767e1b9a15de2f0b08837536109155f28c5392fbb58c34",
       "client_secret" => "a7c0d53db32622482c6aa2ddab159dbea8d9a37d2fd09518cc2e0ec85660ec4cs",
       "code" => "5b0322bc66438b8ee6bce9c9ee7d24150c935784430d3dc421c9bba476ad7c9b",
       "grant_type" => "authorization_code",
       "redirect_uri" => "http://localhost:4000/auth/fitzdares/callback"},
     redirect_uri: "http://localhost:4000/auth/fitzdares/callback", ref: nil,
     request_opts: [], site: "http://localhost:3000",
     strategy: Ueberauth.Strategy.Fitzdares.OAuth, token: nil, token_method: :post,
     token_url: "http://localhost:3000/oauth/token"}

What is weird is that the POST never hits the provider, and I have no idea why. I guess I'm missing something very obvious on why the lib decides that connection has been refused, but for now I'm just losing a truckload of time without may ideas left on how to fix this.
Is there a way to have a better understanding of what's going on there? I enabled debug but I don't see much. Any suggestions?

**Comment by scrogson** [comment]
@ngw very strange.

The best place to start would be to enable tracing in `hackney` with:

```elixir
:hackney_trace.enable(:max, :io)
```

Then make the request and inspect the trace output.

**Comment by ngw** [comment]
I managed to have more output from that, but I can't make any sense of it. I've left some of my debug output as it could eventually help understanding if the params are right.

https://gist.github.com/ngw/c631ac1be3207614ea79671aa6a4f72c

**Comment by ngw** [comment]
I'm looking with suspect at that

    [hackney trace 80 <0.1009.0> 2017:06:12 10:36:40 4486] no socket in the pool 
       Content: [{module,hackney_connect},{line,200},{pool,default}]

My understanding is that it should be very hard to get that problem, and I have no idea how am I causing it.
I'm calling the library like this:

    def get_token!(params \\ [], options \\ []) do
      headers        = Keyword.get(options, :headers, [])
      options        = Keyword.get(options, :options, [])
      client_options = Keyword.get(options, :client_options, [])
      client         = OAuth2.Client.get_token!(client(client_options), params, headers, options)
      client.token
    end

The client looks like this:

    %OAuth2.Client{authorize_url: "http://localhost:3000/oauth/authorize",
     client_id: "9e382aae12f43dc6ae767e1b9a15de2f0b08837536109155f28c5392fbb58c34",
     client_secret: "a7c0d53db32622482c6aa2ddab159dbea8d9a37d2fd09518cc2e0ec85660ec4cs",
     headers: [], params: %{},
     redirect_uri: "http://localhost:4000/auth/fitzdares/callback", ref: nil,
     request_opts: [], site: "http://localhost:3000",
     strategy: Ueberauth.Strategy.Fitzdares.OAuth, token: nil, token_method: :post,
     token_url: "http://localhost:3000/oauth/token"}

I'm on Linux (just to include all infos I got...)

**Comment by ngw** [comment]
Well, it was very difficult to figure out, hopefully if this ever happens again it will be documented.
The problem, as previously described, was that hackney wasn't apparently able to do any request to a service on the same machine, using localhost, 127.0.0.1, 0.0.0.0, and pretty much every other way to refer to the local machine, while curl, using the same arguments, didn't give any problem.
After many tries I noticed with the help of some other guys on Slack that localhost was resolved with its ipv6 ip, ::1, which made me very curious.
I then went to /etc/hosts and removed everything about ipv6, restarted, and voila, everything works again.
I'm not really sure why it behaves like this but here it is, there's no problem with oauth2 or hackney, there's a problem with local configuration.

**Comment by sreecodeslayer** [comment]
Stumbled upon a similar issue.

```elixir
iex> :hackney.request(:post, "https://foo-shop.myshopify.com/admin/oauth/access_token", [], "client_id=<redacted>&client_secret=<redacted>&code=8724aadf31d4da090d96d608b84076e8&grant_type=authorization_code&redirect_uri=https%3A%2F%2Fmyapp.example.com%2Fauth%2Fshopify%2Fcallback", [])
```
```
[hackney trace 80 <8934.3781.0> 2022:01:03 05:01:01 4203] request
   Content: [{module,hackney},
             {line,313},
             {method,post},
             {url,{hackney_url,hackney_ssl,https,
                               <<"foo-shop.myshopify.com">>,
                               <<"/admin/oauth/access_token">>,
                               <<"/admin/oauth/access_token">>,<<>>,<<>>,
                               "foo-shop.myshopify.com",443,<<>>,<<>>}},
             {headers,[]},
             {body,<<"client_id=<redacted>&client_secret=<redacted>&code=8724aadf31d4da090d96d608b84076e8&grant_type=authorization_code&redirect_uri=https%3A%2F%2Fmyapp.example.com%2Fauth%2Fshopify%2Fcallback">>},
             {options,[]}]
[hackney trace 60 <8934.3781.0> 2022:01:03 05:01:01 4203] request without proxy
   Content: [{module,hackney},{line,685}]
[hackney trace 60 <8934.3781.0> 2022:01:03 05:01:01 4203] connect
   Content: [{module,hackney_connect},
             {line,32},
             {transport,hackney_ssl},
             {host,"foo-shop.myshopify.com"},
             {port,443},
             {dynamic,true}]
[hackney trace 80 <8934.3781.0> 2022:01:03 05:01:02 4422] no socket in the pool
   Content: [{module,hackney_pool},{line,88},{pool,default}]
[hackney trace 80 <8934.3781.0> 2022:01:03 05:01:02 4435] connect error
   Content: [{module,hackney_pool},{line,108}]
{:error, :econnrefused}
[hackney trace 80 <8934.3781.0> 2022:01:03 05:01:02 4435] connect error
   Content: [{module,hackney_connect},{line,233}]
```

So I tried the same request with HTTPoison:

```elixir
iex> HTTPoison.post("https://foo-shop.myshopify.com/admin/oauth/access_token", "client_id=<redacted>&client_secret=<redacted>&code=8724aadf31d4da090d96d608b84076e8&grant_type=authorization_code&redirect_uri=https%3A%2F%2Fmyapp.example.com%2Fauth%2Fshopify%2Fcallback")
```
```
[hackney trace 80 <8934.3781.0> 2022:01:03 05:02:33 4877] request
   Content: [{module,hackney},
             {line,313},
             {method,post},
             {url,{hackney_url,hackney_ssl,https,
                               <<"foo-shop.myshopify.com">>,
                               <<"/admin/oauth/access_token">>,
                               <<"/admin/oauth/access_token">>,<<>>,<<>>,
                               "foo-shop.myshopify.com",443,<<>>,<<>>}},
             {headers,[]},
             {body,<<"client_id=<redacted>&client_secret=<redacted>&code=8724aadf31d4da090d96d608b84076e8&grant_type=authorization_code&redirect_uri=https%3A%2F%2Fmyapp.example.com%2Fauth%2Fshopify%2Fcallback">>},
             {options,[{proxy,<<"http://proxy.example.com:4321">>}]}]
[hackney trace 60 <8934.3781.0> 2022:01:03 05:02:33 4877] HTTP proxy request
   Content: [{module,hackney},
             {line,622},
             {url,<<"http://proxy.example.com:4321">>}]
[hackney trace 60 <8934.3781.0> 2022:01:03 05:02:33 4877] connect
   Content: [{module,hackney_connect},
             {line,32},
             {transport,hackney_http_connect},
             {host,"proxy.example.com"},
             {port,4321},
             {dynamic,true}]
[hackney trace 80 <8934.3781.0> 2022:01:03 05:02:33 4891] no socket in the pool
   Content: [{module,hackney_pool},{line,88},{pool,default}]
[hackney trace 80 <8934.3781.0> 2022:01:03 05:02:33 4980] new connection
   Content: [{module,hackney_pool},{line,94}]
[hackney trace 60 <8934.3781.0> 2022:01:03 05:02:33 4980] reuse a connection
   Content: [{module,hackney_connect},{line,216},{pool,default}]
[hackney trace 40 <8934.3781.0> 2022:01:03 05:02:33 4980] perform request
```

cmiiw, but it turns out Hackney is not following the System Env Var HTTP_PROXY and HTTPS_PROXY here, which causes the requests to be `{:error, :econnrefused}` (https://github.com/benoitc/hackney/issues/539)

Solution was to use `request_opts` when creating a new `OAuth2.Client`

```elixir
opts = [
    ...
    authorize_url: "/admin/oauth/authorize",
    token_url: "/admin/oauth/access_token",
    request_opts: [{:proxy, String.to_charlist(System.get_env("HTTP_PROXY"))}],
    ...
]

OAuth2.Client.new(opts)
```
