### ISSUE TITLE
Getting (OAuth2.Error) :closed when calling OAuth2.Client.get_token!/4

### ISSUE THREAD

**Issue by albertchan** [scrogson/oauth2#96]
I've implemented the OAuth2 flow similar to the example. I'm connecting to Microsoft's Azure OAuth2 provider. My auth flow works in the development environment, but when I try to deploy it to our production environment with SSL, I get the following error when I reach the `get_token` portion of the code in which I try to request for an `access_token`.

```
Request: GET /auth/callback?code=<omitted>&session_state=<omitted>
** (exit) an exception was raised:
    ** (OAuth2.Error) :closed
        (oauth2) lib/oauth2/client.ex:248: OAuth2.Client.get_token!/4
        (arrow_directory) web/controllers/auth_controller.ex:33: ArrowDirectory.AuthController.callback/2
        (arrow_directory) web/controllers/auth_controller.ex:1: ArrowDirectory.AuthController.action/2
        (arrow_directory) web/controllers/auth_controller.ex:1: ArrowDirectory.AuthController.phoenix_controller_pipeline/2
        (arrow_directory) lib/arrow_directory/endpoint.ex:1: ArrowDirectory.Endpoint.instrument/4
        (arrow_directory) lib/phoenix/router.ex:261: ArrowDirectory.Router.dispatch/2
        (arrow_directory) web/router.ex:1: ArrowDirectory.Router.do_call/2
        (arrow_directory) lib/arrow_directory/endpoint.ex:1: ArrowDirectory.Endpoint.phoenix_pipeline/1
        (arrow_directory) lib/plug/debugger.ex:123: ArrowDirectory.Endpoint."call (overridable 3)"/2
        (arrow_directory) lib/arrow_directory/endpoint.ex:1: ArrowDirectory.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /opt/app/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

What would cause the `:closed` exception?

**Comment by scrogson** [comment]
Hi @albertchan,

This looks like the connection is being closed for some reason. This is coming from the underlying HTTP client (hackney). Most likely it is returning `{:error, :closed}` when the request was made. 

Since you are using `get_token!` you are getting an exception for this. If you remove the `!` you should get `{:error, :closed}` instead.

You can start debugging this in 2 ways:

1. Turn on debugging in the `OAuth2` app:
 
```ex
config :oauth2, debug: true
```

2. Enable tracing in hackney:

```ex
:hackney_trace.enable(:max, :io)
```
